export const URL_SERVICIOS = "https://prueba.midisappsalud.com/api";
export const URL = "http://127.0.0.1:8080/infociad_angular/src/server";
export const SERVICES = {
    LOGIN:'/login/login.php',
    GET_USUARIOS:'/usuarios/getUsuarios.php',
    GET_TIPO_USUARIO:"/usuarios/getTipoUsuario.php",
    EDITAR_USUARIOS:"/usuarios/updateUsuario.php",
	ADD_USUARIO:"/usuarios/addAgregarUsuario.php",
	GET_USUARIO_ID:"/usuarios/getUsuariosId.php",
	DELETE_USUARIO:"/usuarios/deleteUsuario.php",
	GET_CLIENTES:"/cliente/getClientes.php",
	UPDATE_CLIENTES:"/cliente/updateClientes.php",
	DELETE_CLIENTE:"/cliente/deleteClientes.php",
	ADD_CLIENTE:"/cliente/addClientes.php",
	GET_PROYECTOS:"/proyecto/getProyecto.php",
	UPDATE_PROYECTOS:"/proyecto/updateProyecto.php",
	DELETE_PROYECTO:"/proyecto/deleteProyecto.php",
	ADD_PROYECTO:"/proyecto/addProyecto.php",
	//GET_OBJETIVOS:"/objetivo/getObjetivo.php",
	GET_OBJETIVOS:"/objetivo/getObjetivoEspecifico.php",
	UPDATE_OBJETIVOS:"/objetivo/updateObjetivo.php",
	DELETE_OBJETIVOS:"/objetivo/deleteObjetivo.php",
	ADD_OBJETIVOS:"/objetivo/addObjetivo.php",
	ADD_OBJETIVOS_ESPECIFICOS:"/objetivo/addObjetivoEspecifico.php",
	UPDATE_OBJETIVOS_ESPECIFICOS:"/objetivo/updateObjetivoEspecifico.php",
	GET_OBJETIVOS_ESPECIFICOS:"/objetivo/getObjetivoEspecifico.php",
	GET_ENTREGABLES:"/entregable/getEntregable.php",
	GET_ENTREGABLES_COMPLETO:"/entregable/getEntregableCompleto.php",
	UPDATE_ENTREGABLES:"/entregable/updateEntregable.php",
	ADD_ENTREGABLES:"/entregable/addEntregable.php",
	DELETE_ENTREGABLES:"/entregable/deleteEntregable.php",
	ETAPAS_PROCESO_COMPLETO:"/etapas_proceso/getEtapasProcesoCompleto.php",
	GET_ETAPAS_PROCESO:"/etapas_proceso/getEtapasProceso.php",
	GET_PROCESO_COMPLETO:"/etapas_proceso/getEtapasProcesoAgrupacion.php",
	DETALLE_ETAPA_PROCESO:"/etapas_proceso/getDetalleEtapasProceso.php",
	GET_REUNIONES: "/reuniones/getReunion.php",
	ADD_REUNIONES: "/reuniones/addReunion.php",
	GET_DETALLE_REUNION: "/detalle_reunion/getDetalleReunion.php",
	EDIT_REUNIONES: "/reuniones/updateReunion.php",
	ADD_DETALLE_REUNIONES:"/detalle_reunion/addDetalleReunion.php",
	UPDATE_DETALLE_REUNIONES:"/detalle_reunion/updateDetalleReunion.php",
	GET_ANEXOS_REUNIONES:"/detalle_reunion/getAnexosDetalleReunion.php",
	DELETE_ANEXO_REUNION:"/detalle_reunion/deleteAnexosDetalleReunion.php",
	DELETE_REUNION:"/reuniones/deleteReunion.php",
	DELETE_DETALLE_REUNION:"/detalle_reunion/deleteDetalleReunion.php",
	ADD_ANEXO_ETAPA:"/anexos_etapa_proceso/addAnexoEtapaProceso.php",
	GET_PROCESOS_USUARIOS:"/gantt/getProcesosUsuario.php",
	ADD_SOLICITUD:"/solicitud/addSolicitud.php",
	GET_SOLICITUDES:"/solicitud/getSolicitudes.php",
	UPDATE_SOLICITUD:"/solicitud/updateSolicitud.php",
	DELETE_SOLICITUD:"/solicitud/deleteSolicitud.php",
	ADD_AGRUPACION_PROCESO:"/etapas_proceso/addEtapaProceso.php",
	GET_AGRUPACION_PROCESO:"/etapas_proceso/getAgrupacionSencilla.php",
	GET_DETALLE_ETAPA_PROCESO: "/anexos_etapa_proceso/getDetalleEtapaProceso.php",
	GET_ANEXOS_ETAPA_PROCESO: "/anexos_etapa_proceso/getAnexosEtapaProceso.php",
	DELETE_DETALLE_ANEXO:"/anexos_etapa_proceso/deleteAnexoEtapaProceso.php",
	DELETE_AVANCE_DETALLE:"/anexos_etapa_proceso/deleteDetalleEtapaProceso.php",
	EDIT_AVANCE_ENTREGABLE:"/anexos_etapa_proceso/updateAnexoEtapaProceso.php",
	DELETE_ETAPA_PROCESO:"/etapas_proceso/deleteEtapaProceso.php",
	DELETE_ETAPA_PROCESO_COMPLETA:"/etapas_proceso/deleteEtapaProcesoAgrupacion.php",

	
	DETAIL_ETAPA_PROCESO: "/etapas_proceso/getEtapasProcesoIndividual.php",
	UPDATE_ETAPA_PROCESO:"/etapas_proceso/updateEtapasProcesoIndividual.php",
	UPDATE_PROCESO_COMPLETO:"/etapas_proceso/updateEtapaProceso.php",
	ADD_ASISTENTES_REUNION:"/reuniones/addAsistentesReunion.php",
	GET_ASISTENTES_REUNION:"/reuniones/getAsistentesReunion.php",
	UPDATE_ASISTENTES_REUNION:"/reuniones/updateAsistentesReunion.php",
	DELETE_OBJETIVO_ESPECIFICO:"/objetivo/deleteObjetivoEspecifico.php",
	CONSOLIDADO_USUARIO:"/usuarios/getProcesosUsuario.php",
	CRUCE_FECHA_ENTREGBABLE:"/entregable/getCruceEntregables.php"
};
